services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: taxemon
    ports:
      - "7843:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
