// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql"
)

type AssociatedAccount struct {
	Address       string         `db:"address" json:"address"`
	LastSignature sql.NullString `db:"last_signature" json:"last_signature"`
	Type          int64          `db:"type" json:"type"`
	Data          sql.NullString `db:"data" json:"data"`
}

type Event struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	IxIdx         int64  `db:"ix_idx" json:"ix_idx"`
	Idx           int64  `db:"idx" json:"idx"`
	Type          int64  `db:"type" json:"type"`
	Data          string `db:"data" json:"data"`
}

type InnerInstruction struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	IxIdx         int64  `db:"ix_idx" json:"ix_idx"`
	Idx           int64  `db:"idx" json:"idx"`
	ProgramIDIdx  int64  `db:"program_id_idx" json:"program_id_idx"`
	AccountsIdxs  string `db:"accounts_idxs" json:"accounts_idxs"`
	Data          string `db:"data" json:"data"`
}

type Instruction struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	Idx           int64  `db:"idx" json:"idx"`
	IsKnown       bool   `db:"is_known" json:"is_known"`
	ProgramIDIdx  int64  `db:"program_id_idx" json:"program_id_idx"`
	AccountsIdxs  string `db:"accounts_idxs" json:"accounts_idxs"`
	Data          string `db:"data" json:"data"`
}

type SyncRequest struct {
	ID        int64 `db:"id" json:"id"`
	WalletID  int64 `db:"wallet_id" json:"wallet_id"`
	CreatedAt int64 `db:"created_at" json:"created_at"`
}

type Transaction struct {
	ID         int64          `db:"id" json:"id"`
	Signature  string         `db:"signature" json:"signature"`
	Timestamp  int64          `db:"timestamp" json:"timestamp"`
	Slot       int64          `db:"slot" json:"slot"`
	BlockIndex sql.NullInt64  `db:"block_index" json:"block_index"`
	Err        bool           `db:"err" json:"err"`
	ErrMsg     sql.NullString `db:"err_msg" json:"err_msg"`
}

type TransactionAccount struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	Address       string `db:"address" json:"address"`
	Idx           int64  `db:"idx" json:"idx"`
}

type TransactionLog struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	Idx           int64  `db:"idx" json:"idx"`
	Log           string `db:"log" json:"log"`
}

type TransactionToWallet struct {
	WalletID      int64 `db:"wallet_id" json:"wallet_id"`
	TransactionID int64 `db:"transaction_id" json:"transaction_id"`
}

type VInnerInstruction struct {
	TransactionID  int64  `db:"transaction_id" json:"transaction_id"`
	IxIdx          int64  `db:"ix_idx" json:"ix_idx"`
	ProgramAddress string `db:"program_address" json:"program_address"`
	AccountsIdxs   string `db:"accounts_idxs" json:"accounts_idxs"`
	Data           string `db:"data" json:"data"`
}

type VInstruction struct {
	TransactionID  int64       `db:"transaction_id" json:"transaction_id"`
	IsKnown        bool        `db:"is_known" json:"is_known"`
	Idx            int64       `db:"idx" json:"idx"`
	ProgramAddress string      `db:"program_address" json:"program_address"`
	AccountsIdxs   string      `db:"accounts_idxs" json:"accounts_idxs"`
	Data           string      `db:"data" json:"data"`
	InnerIxs       interface{} `db:"inner_ixs" json:"inner_ixs"`
}

type VTransaction struct {
	Signature    string      `db:"signature" json:"signature"`
	ID           int64       `db:"id" json:"id"`
	Accounts     interface{} `db:"accounts" json:"accounts"`
	Logs         interface{} `db:"logs" json:"logs"`
	Instructions interface{} `db:"instructions" json:"instructions"`
}

type VTransactionAccount struct {
	TransactionID int64       `db:"transaction_id" json:"transaction_id"`
	Addresses     interface{} `db:"addresses" json:"addresses"`
}

type VTransactionLog struct {
	TransactionID int64       `db:"transaction_id" json:"transaction_id"`
	Logs          interface{} `db:"logs" json:"logs"`
}

type Wallet struct {
	ID            int64          `db:"id" json:"id"`
	Address       string         `db:"address" json:"address"`
	Label         sql.NullString `db:"label" json:"label"`
	LastSignature sql.NullString `db:"last_signature" json:"last_signature"`
}
