// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"database/sql"
)

type InnerInstruction struct {
	TransactionID  int64          `db:"transaction_id" json:"transaction_id"`
	IxIdx          int64          `db:"ix_idx" json:"ix_idx"`
	Idx            int64          `db:"idx" json:"idx"`
	ProgramIDIndex int64          `db:"program_id_index" json:"program_id_index"`
	AccountsIds    sql.NullString `db:"accounts_ids" json:"accounts_ids"`
	Data           []byte         `db:"data" json:"data"`
}

type Instruction struct {
	TransactionID  int64          `db:"transaction_id" json:"transaction_id"`
	Idx            int64          `db:"idx" json:"idx"`
	ProgramIDIndex int64          `db:"program_id_index" json:"program_id_index"`
	AccountsIds    sql.NullString `db:"accounts_ids" json:"accounts_ids"`
	Data           []byte         `db:"data" json:"data"`
}

type Transaction struct {
	ID         int64          `db:"id" json:"id"`
	Signature  string         `db:"signature" json:"signature"`
	Timestamp  int64          `db:"timestamp" json:"timestamp"`
	Slot       int64          `db:"slot" json:"slot"`
	BlockIndex sql.NullInt64  `db:"block_index" json:"block_index"`
	Err        bool           `db:"err" json:"err"`
	ErrMsg     sql.NullString `db:"err_msg" json:"err_msg"`
}

type TransactionAccount struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	Address       string `db:"address" json:"address"`
	Idx           int64  `db:"idx" json:"idx"`
}

type TransactionLog struct {
	TransactionID int64  `db:"transaction_id" json:"transaction_id"`
	Idx           int64  `db:"idx" json:"idx"`
	Log           string `db:"log" json:"log"`
}

type VInnerInstruction struct {
	Address     string         `db:"address" json:"address"`
	AccountsIds sql.NullString `db:"accounts_ids" json:"accounts_ids"`
	Data        []byte         `db:"data" json:"data"`
}

type VInstruction struct {
	Address           string         `db:"address" json:"address"`
	TransactionID     int64          `db:"transaction_id" json:"transaction_id"`
	AccountsIds       sql.NullString `db:"accounts_ids" json:"accounts_ids"`
	Data              []byte         `db:"data" json:"data"`
	InnerInstructions interface{}    `db:"inner_instructions" json:"inner_instructions"`
}

type VTransaction struct {
	Signature   string      `db:"signature" json:"signature"`
	ID          int64       `db:"id" json:"id"`
	Accounts    interface{} `db:"accounts" json:"accounts"`
	Logs        interface{} `db:"logs" json:"logs"`
	Instruction interface{} `db:"instruction" json:"instruction"`
}
