// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package dbgen

import (
	"context"
	"strings"
)

const fetchTransactions = `-- name: FetchTransactions :many
SELECT
    signature, id, accounts, logs, instruction
FROM
    v_transaction tx
WHERE
    tx.signature IN (/*SLICE:signatures*/?)
`

func (q *Queries) FetchTransactions(ctx context.Context, signatures []string) ([]*VTransaction, error) {
	query := fetchTransactions
	var queryParams []interface{}
	if len(signatures) > 0 {
		for _, v := range signatures {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:signatures*/?", strings.Repeat(",?", len(signatures))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:signatures*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*VTransaction
	for rows.Next() {
		var i VTransaction
		if err := rows.Scan(
			&i.Signature,
			&i.ID,
			&i.Accounts,
			&i.Logs,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
